# Generated by Django 5.0.3 on 2024-04-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox", "0002_dropbox_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PyScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("py_file", models.FileField(upload_to="py_file")),
                ("py_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
