# Generated by Django 5.0.3 on 2024-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox", "0003_pyscript"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task_file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
