# Generated by Django 5.0.3 on 2024-04-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox", "0004_task_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="xfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data", models.BinaryField()),
            ],
        ),
    ]
