# Generated by Django 5.0.3 on 2024-04-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox", "0005_xfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropbox",
            name="excel",
            field=models.FileField(null=True, upload_to="excels/"),
        ),
    ]
