# Generated by Django 5.0.3 on 2024-04-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropbox", "0006_dropbox_excel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropbox",
            name="excel",
            field=models.FileField(null=True, upload_to="files/"),
        ),
    ]
