# Generated by Django 5.0.3 on 2024-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amwell_boa_bank_rec",
            name="status",
        ),
        migrations.AddField(
            model_name="amwell_boa_bank_rec",
            name="csv_upload",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="amwell_boa_bank_rec",
            name="excel_upload",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
