# Generated by Django 5.0.3 on 2024-04-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_remove_amwell_boa_bank_rec_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amwell_boa_bank_rec",
            name="excel_upload",
            field=models.FileField(null=True, upload_to="excel/"),
        ),
    ]
