# Generated by Django 5.0.3 on 2024-04-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_alter_amwell_boa_bank_rec_excel_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amwell_boa_bank_rec",
            name="csv_upload",
            field=models.FileField(null=True, upload_to="csv/"),
        ),
    ]
